### Query the Demo endpoint
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}

###
GET http://localhost:8765/api/orders
Authorization: Bearer {{auth-token}}

###
GET http://localhost:8765/api/customer/orders
Authorization: Bearer {{auth-token}}

###
POST http://localhost:8765/api/auth/register
Content-Type: application/json

{
  "name": "아무개",
  "email":  "anybody123@mail.com",
  "password": "password",
  "role":  "CUSTOMER"
}



###
POST http://localhost:8765/api/auth/register
Content-Type: application/json

{
  "name": "아무개",
  "email":  "anybody@mail.com",
  "password": "password",
  "role":  "SELLER"
}

### Login with 아무개
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "anybody123@mail.com",
  "password": "password"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}

### Login with Heemin
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "qqwqwqw@mail.com",
  "password": "password"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}


###
POST http://localhost:8765/api/customers/customer-detail
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "age" : "25",
  "gender" : "1",
  "address" : "Waterloo, ON, Canada"
}

###
POST http://localhost:8765/api/customer/orders
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "itemName" : "Smartphone",

  "sellerName" : "아무개",

  "price" : "100000",

  "quantity" : "5"
}

###
GET http://localhost:8765/api/customer/orders
Authorization: Bearer {{auth-token}}

###
GET http://localhost:8765/api/customer/orders/confirmed
Authorization: Bearer {{auth-token}}


###
PATCH http://localhost:8765/api/customer/orders/2/confrimed
Authorization: Bearer {{auth-token}}


###
GET http://localhost:8765/api/orders/?customer-email=heem6woo@gmail.com
Authorization: Bearer {{auth-token}}


###
POST http://localhost:8765/api/items/rollback
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "itemValues": {
    "itemId": 1,
    "category": 1,
    "itemName": "Smartphone",
    "itemDescription": "High-performance smartphone with advanced features",
    "req_Dt": "2024-05-09T01:03:09.000000"
  },
  "salesValues": {
    "salesId": 1,
    "sellerId": 1,
    "itemId": 1,
    "itemCount": 100,
    "itemPrice": 100000,
    "itemStatus": 1
  }
}

###
GET http://localhost:8765/api/item-search/getitems/?item-name=s
Authorization: Bearer {{auth-token}}

###
GET http://localhost:8765/api/item-search/getitem/?item-name=Smartphone&seller-id=2
Authorization: Bearer {{auth-token}}
