

server:
  port: 8000

spring:
  application:
    name: review-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://wittdbreal.chr10oalkvb3.ap-northeast-2.rds.amazonaws.com:3306/review_directory
    username: admin
    password: RKAWK78044*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: update
      properties:
        hibernate.format_sql: true
    database: mysql

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

#
# Grpc Settings
#
grpc:
  client:
    member-service:
      address: 'discovery:///member-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    item-service:
      address: 'discovery:///item-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext



