spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:mysql://wittdbreal.chr10oalkvb3.ap-northeast-2.rds.amazonaws.com:3306/Vga
    username: admin
    password: RKAWK78044*
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
server:
  port: 8080

jwt:
  key:
    jwtSecret: "bXlTdXBlclNlY3VyZVNlY3JldEtleUZvckpXVFNlY3VyaXR5SW1wbGVtZW50YXRpb24gV2l0aCBMb25nIGVuYW91Z2ggYnl0ZXMoTGlrZSBvdmVyIDMyc2J5dGVzKQ=="
  live:
    rtk: 500000
    atk: 50000
  name:
    rtk: "RTK"
    atk: "ATK"


