
### Query the Demo endpoint
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}


###
GET http://localhost:8765/api/reviews/?customer-email=heem6woo@gmail.com
Authorization: Bearer {{auth-token}}

###
GET http://localhost:8765/api/reviews/?score=3
Authorization: Bearer {{auth-token}}

###
GET http://localhost:8765/api/reviews/?customer-email=heem6woo@gmail.com&?score=3
Authorization: Bearer {{auth-token}}
