### Query the Demo endpoint
POST http://localhost:8765/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}


###
GET http://localhost:8765/api/v1/logout
Authorization: Bearer {{refresh-token}}

###
POST http://localhost:8765/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}

> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}



### Query the Demo endpoint
GET http://localhost:8080/api/v1/demo-controller
Authorization: Bearer {{auth-token}}


### Change the password
PATCH http://localhost:8765/api/v1/change-password
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "password123",
  "newPassword": "newPassword",
  "confirmationPassword":  "newPassword"
}

### Login again and update the token
POST http://localhost:8765/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "newPassword"
}

> {% client.global.set("new-auth-token", response.body.accessToken);
    client.global.set("new-refresh-token", response.body.refreshToken);%}


### Query the Demo endpoint after password change
GET http://localhost:8765/api/v1/logout
Authorization: Bearer {{new-refresh-token}}

###
POST http://localhost:8765/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password"
}

> {% client.global.set("new-auth-token", response.body.accessToken);
    client.global.set("new-refresh-token", response.body.refreshToken);%}
