
### Query the Demo endpoint
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}

### Query the Demo endpoint
GET http://localhost:8765/api/demo-controller
Authorization: Bearer {{auth-token}}
