
### Register User
POST http://localhost:8765/api/auth/register
Content-Type: application/json

{
  "name": "홍길동",
  "email":  "hongildong@mail.com",
  "password": "password",
  "role":  "CUSTOMER"
}
### Register User
POST http://localhost:8765/api/auth/register
Content-Type: application/json

{
  "name": "아무개",
  "email":  "anybody@mail.com",
  "password": "password",
  "role":  "SELLER"
}

### Query the Demo endpoint
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}
> {% client.global.set("admin-auth-token", response.body.accessToken);
    client.global.set("admin-refresh-token", response.body.refreshToken);%}

### Query the Demo endpoint
POST http://localhost:8765/api/auth/authenticate
Content-Type: application/json

{
  "email":  "hongildong@mail.com",
  "password": "password"
}
> {% client.global.set("customer-auth-token", response.body.accessToken);
    client.global.set("customer-refresh-token", response.body.refreshToken);%}


### Query the ADMIN Demo endpoint
GET http://localhost:8765/api/members
Authorization: Bearer {{admin-auth-token}}

###
GET http://localhost:8765/api/members
Authorization: Bearer {{customer-auth-token}}




