### Query the Demo endpoint
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "heem6woo@gmail.com",
  "password": "password123"
}
> {% client.global.set("admin-auth-token", response.body.accessToken);
    client.global.set("admin-refresh-token", response.body.refreshToken);%}

### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "아무개",
  "email":  "anybody@mail.com",
  "password": "password",
  "role":  "SELLER"
}

### Query the ADMIN Demo endpoint
GET http://localhost:8080/api/v1/members
Authorization: Bearer {{admin-auth-token}}

### Query the ADMIN Demo endpoint
PATCH http://localhost:8080/api/v1/members/grant-permission
Authorization: Bearer {{admin-auth-token}}
Content-Type: application/json

{
  "password": "password123",
  "email":  "anybody@mail.com",
  "role":  "ADMIN"
}


### Login with 아무개
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "anybody@mail.com",
  "password": "password"
}
> {% client.global.set("auth-token", response.body.accessToken);
    client.global.set("refresh-token", response.body.refreshToken);%}


### Query the ADMIN Demo endpoint
GET http://localhost:8080/api/v1/members
Authorization: Bearer {{auth-token}}


