DROP SCHEMA IF EXISTS `review_driectory`;

CREATE SCHEMA `review_driectory`;

use `review_driectory`;

CREATE TABLE `review` (
  `id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `item_id` int NOT NULL,
  `contains` varchar(400) DEFAULT NULL,
  `date` timestamp DEFAULT NULL,
  `score` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (1, 2, 2, 2, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2023-12-19 21:57:33', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (2, 3, 3, 3, 'Morbi quis tortor id nulla ultrices aliquet.', '2023-05-10 21:39:33', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (3, 4, 4, 4, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '2023-07-27 11:29:26', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (4, 5, 5, 5, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2023-11-03 22:46:30', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (5, 6, 1, 6, 'Sed accumsan felis.', '2024-02-02 18:16:33', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (6, 7, 2, 7, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2023-10-16 18:47:41', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (7, 8, 3, 8, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '2024-02-13 06:17:26', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (8, 9, 4, 9, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2023-09-12 21:13:07', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (9, 10, 5, 10, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2023-09-15 04:17:37', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (10, 1, 1, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2024-03-22 20:19:16', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (11, 2, 2, 2, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2023-11-15 20:35:09', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (12, 3, 3, 3, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2024-02-13 22:55:43', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (13, 4, 4, 4, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2023-06-09 09:07:11', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (14, 5, 5, 5, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '2023-07-23 20:02:06', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (15, 6, 1, 6, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', '2023-12-15 11:32:46', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (16, 7, 2, 7, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2024-03-20 05:51:03', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (17, 8, 3, 8, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2024-01-03 23:11:01', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (18, 9, 4, 9, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2024-01-08 09:39:54', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (19, 10, 5, 10, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2024-01-11 19:36:14', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (20, 1, 1, 1, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2023-12-20 21:49:16', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (21, 2, 2, 2, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', '2023-12-29 14:45:00', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (22, 3, 3, 3, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2023-08-19 11:20:45', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (23, 4, 4, 4, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2024-03-05 02:34:56', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (24, 5, 5, 5, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', '2023-06-19 04:33:00', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (25, 6, 1, 6, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2023-12-29 03:05:06', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (26, 7, 2, 7, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', '2023-05-30 23:19:49', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (27, 8, 3, 8, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2024-02-10 16:58:33', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (28, 9, 4, 9, 'Morbi non quam nec dui luctus rutrum.', '2024-03-15 00:12:12', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (29, 10, 5, 10, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2023-05-15 07:55:57', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (30, 1, 1, 1, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2023-09-15 21:08:45', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (31, 2, 2, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2024-01-20 17:09:47', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (32, 3, 3, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2023-08-27 14:39:00', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (33, 4, 4, 4, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2023-08-14 10:53:40', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (34, 5, 5, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2023-07-23 04:38:39', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (35, 6, 1, 6, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2023-05-26 15:52:11', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (36, 7, 2, 7, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2024-02-24 21:14:27', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (37, 8, 3, 8, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2024-01-27 07:05:45', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (38, 9, 4, 9, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2023-05-13 06:16:32', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (39, 10, 5, 10, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2024-04-17 05:18:46', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (40, 1, 1, 1, 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', '2023-11-26 03:47:26', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (41, 2, 2, 2, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2023-09-15 19:13:39', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (42, 3, 3, 3, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '2023-07-26 05:00:07', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (43, 4, 4, 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2024-04-01 15:44:49', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (44, 5, 5, 5, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '2023-10-27 00:24:13', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (45, 6, 1, 6, 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2023-10-09 10:29:30', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (46, 7, 2, 7, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2023-06-16 10:39:51', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (47, 8, 3, 8, 'Proin eu mi.', '2024-03-13 10:13:46', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (48, 9, 4, 9, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '2023-11-27 05:40:43', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (49, 10, 5, 10, 'Proin eu mi.', '2023-08-30 05:05:36', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (50, 1, 1, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', '2023-12-05 01:03:03', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (51, 2, 2, 2, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2023-10-26 07:04:44', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (52, 3, 3, 3, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2024-02-01 09:48:17', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (53, 4, 4, 4, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2023-05-19 10:35:13', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (54, 5, 5, 5, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2023-06-22 03:29:27', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (55, 6, 1, 6, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2023-06-04 00:05:38', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (56, 7, 2, 7, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2023-06-11 10:14:18', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (57, 8, 3, 8, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '2023-08-12 20:34:46', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (58, 9, 4, 9, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2023-07-25 12:08:59', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (59, 10, 5, 10, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2024-04-15 21:32:12', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (60, 1, 1, 1, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '2024-03-05 08:26:09', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (61, 2, 2, 2, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2023-09-16 06:40:40', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (62, 3, 3, 3, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '2023-09-27 07:40:19', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (63, 4, 4, 4, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2023-11-26 17:44:14', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (64, 5, 5, 5, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2023-07-25 19:09:34', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (65, 6, 1, 6, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '2024-04-22 06:30:06', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (66, 7, 2, 7, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '2023-11-14 13:04:49', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (67, 8, 3, 8, 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2023-06-28 18:04:27', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (68, 9, 4, 9, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2023-09-30 15:53:44', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (69, 10, 5, 10, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2023-12-31 16:19:41', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (70, 1, 1, 1, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '2023-08-30 04:13:35', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (71, 2, 2, 2, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2023-08-07 20:24:35', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (72, 3, 3, 3, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2023-10-23 10:11:33', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (73, 4, 4, 4, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2023-12-02 20:26:25', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (74, 5, 5, 5, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2024-03-31 21:19:42', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (75, 6, 1, 6, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2024-01-29 18:27:07', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (76, 7, 2, 7, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2024-04-15 17:14:23', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (77, 8, 3, 8, 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2023-11-02 02:46:04', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (78, 9, 4, 9, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2023-07-10 07:49:36', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (79, 10, 5, 10, 'Sed vel enim sit amet nunc viverra dapibus.', '2023-10-03 04:47:21', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (80, 1, 1, 1, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2023-07-08 07:04:15', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (81, 2, 2, 2, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2023-05-20 21:23:19', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (82, 3, 3, 3, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '2024-01-19 00:44:59', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (83, 4, 4, 4, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2024-03-09 06:22:52', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (84, 5, 5, 5, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '2024-01-08 08:10:58', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (85, 6, 1, 6, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2024-02-28 11:34:03', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (86, 7, 2, 7, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '2024-03-11 03:55:47', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (87, 8, 3, 8, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2024-03-17 10:09:21', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (88, 9, 4, 9, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2023-07-16 12:22:52', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (89, 10, 5, 10, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', '2024-02-08 19:31:04', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (90, 1, 1, 1, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2024-03-12 09:58:15', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (91, 2, 2, 2, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', '2023-12-19 18:28:28', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (92, 3, 3, 3, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2023-07-08 05:07:28', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (93, 4, 4, 4, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2023-09-25 23:58:01', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (94, 5, 5, 5, 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2024-01-02 20:33:27', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (95, 6, 1, 6, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2024-04-26 15:34:53', 1);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (96, 7, 2, 7, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', '2024-03-27 22:18:00', 2);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (97, 8, 3, 8, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', '2023-08-30 10:43:57', 3);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (98, 9, 4, 9, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2024-03-31 01:36:10', 4);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (99, 10, 5, 10, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2023-09-13 04:49:21', 5);
insert into review (id, customer_id, seller_id, item_id, contains, date, score) values (100, 1, 1, 1, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2024-02-02 02:20:16', 1);
